environment:
  GIT_REPOSITORY: https://github.com/wheeler-microfluidics/constructor-git.git
  matrix:
    - PYTHON_VERSION: 2.7
      MINICONDA: C:\Miniconda
      PYTHON_ARCH: "32"

init:
  - ECHO %PYTHON_VERSION% %MINICONDA%
  - set appVeyorBuildVersion=%appveyor_build_version%
  - echo appVeyorBuildVersion:%appVeyorBuildVersion%
  - set branch=%APPVEYOR_REPO_BRANCH%
  - echo branch:%branch%
  - set gitVersion=%branch:~-3%
  - echo gitversion:%gitVersion%
  - set newVersion=%gitVersion%.%APPVEYOR_BUILD_NUMBER%
  - echo %newVersion%
  - appveyor UpdateBuild -Version "%newVersion%"

install:
  # Exit if no .conda-recipe folder
  - ps: if(!(Test-Path ".conda-recipe")){Add-AppveyorMessage -Message "No Conda Recipe Found" -Category "Error"; throw "Missing .conda-recipe folder"}
  - git clone --depth=1 https://github.com/sci-bots/sci-bots-configs.git
  - powershell -executionpolicy remotesigned -File .\sci-bots-configs\appveyor-install.ps1

# Handle build and tests using conda (defined in .conda-recipe/meta.yaml)
build: false
test_script:
  - echo Build Complete

after_test:
  - powershell -executionpolicy remotesigned -File .\sci-bots-configs\appveyor-after-test.ps1